### ISSUE TITLE
Can someone plzzzz add a junit test based on this please (((

### ISSUE THREAD

**Issue by ymolists** [neo4j-examples/movies-java-spring-data-neo4j#1]
I am looking all over the net and cant find anything remotely working so far for sdn4.

Apart from mentioning the inclusion of junit:junti in the gradle build the docs at http://spring.io/guides/gs/accessing-data-neo4j/ do not cover this explicitly. Most of the help i can get from the web is based on the old pre sdn 4 libs configuration.

Also would be helpful to see a gradle based build here )))

Here is what i have so far in my gradle file:

apply plugin: 'spring-boot'
apply plugin: 'io.spring.dependency-management'

ext {

```
neo4jVersion  = ''
//neo4jVersion  = '2.2.5'

neo4jOgmVersion  = ''
//neo4jOgmVersion  = '1.0.0.M1'

springVersion  = ""
//springVersion  = "4.2.1.RELEASE"

//springNeo4jVersion  =''
springNeo4jVersion  =':4.0.0.RELEASE'
```

}

dependencies {
    testCompile("junit:junit:4.12")
    testCompile("org.springframework:spring-test${springVersion}")

```
testCompile "org.neo4j:neo4j-ogm-test:${neo4jOgmVersion}"
testCompile "org.neo4j:neo4j-kernel:${neo4jVersion}:tests@jar"
testCompile "org.neo4j.app:neo4j-server:${neo4jVersion}:tests@jar"

compile("javax.el:javax.el-api:2.2.4")
compile("org.hibernate:hibernate-validator")

compile("org.springframework:spring-tx${springVersion}")
compile("org.springframework:spring-context${springVersion}")
compile("org.springframework.boot:spring-boot-starter${springVersion}")
compile("org.springframework.data:spring-data-neo4j${springNeo4jVersion}")
```

}

**Comment by pdtyreus** [comment]
I know this is old, but you can take a look at [this PR](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/pull/4) for some JUnit testing examples using profiles and an embedded database.

**Comment by mangrish** [comment]
@ymolists: Is this still an issue for you?

**Comment by ymolists** [comment]
I moved jobs :)) you can go ahead and close this. And thank you for asking :))

**Comment by michael-simons** [comment]
Closing this.
