### ISSUE TITLE
Example is not working.

### ISSUE THREAD

**Issue by wkaczurba** [neo4j-examples/movies-java-spring-data-neo4j#10]
Followed the instruction and Maven fails to resolve dependencies:

> [INFO] Scanning for projects...
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building SDN4 University 0.0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] >>> spring-boot-maven-plugin:1.5.0.BUILD-SNAPSHOT:run (default-cli) > test-compile @ sdn4-movies >>>
> [WARNING] The POM for org.springframework.data:spring-data-neo4j:jar:4.2.1.BUILD-SNAPSHOT is missing, no dependency information available
> [WARNING] The POM for org.springframework.data:spring-data-rest-webmvc:jar:2.6.1.BUILD-SNAPSHOT is missing, no dependency information available
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.786 s
> [INFO] Finished at: 2017-01-31T13:47:11+00:00
> [INFO] Final Memory: 16M/160M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project sdn4-movies: Could not resolve dependencies for project com.neo4j.examples:sdn4-movies:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.springframework.data:spring-data-neo4j:jar:4.2.1.BUILD-SNAPSHOT, org.springframework.data:spring-data-rest-webmvc:jar:2.6.1.BUILD-SNAPSHOT: Failure to find org.springframework.data:spring-data-neo4j:jar:4.2.1.BUILD-SNAPSHOT in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
>

**Comment by mangrish** [comment]
Seems to work now. Please try again and reopen if that's not the case.
