### ISSUE TITLE
Session Bean not found

### ISSUE THREAD

**Issue by MartinX3** [neo4j-examples/movies-java-spring-data-neo4j#18]
- [X] Ubuntu Mate 17.04 x64   
- [X] IntelliJ Ultimate 2017.2
- [X] Java 8
- [x] Spring Boot 1.5.6
- [x] Neo4J 3.1.2

#MovieRepositoryTest.java

```
@Autowired
	private Session session;
```

> Could not autowire. No beans of 'Session' type found.
Checks autowiring problems in a bean class.

The following removed the Files

- src/main/java/movies/spring/data/neo4j/MyNeo4jConfiguration.java
- src/main/java/movies/spring/data/neo4j/MyNeo4jTestConfiguration.java

which provided the bean:
[6c91335ce31d9a1ee0c2a6bbf44ed723324580a2](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/commit/6c91335ce31d9a1ee0c2a6bbf44ed723324580a2)

**Comment by MartinX3** [comment]
Solution?

```
package de.predic8.demo.neo4j.config;

import org.neo4j.ogm.session.Session;
import org.neo4j.ogm.session.SessionFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.neo4j.repository.config.EnableNeo4jRepositories;
import org.springframework.data.neo4j.transaction.Neo4jTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;

@Configuration
@EnableNeo4jRepositories(basePackages = "de.xxx.demo.neo4j.repository")
@EnableTransactionManagement
public class Neo4JConfig {
    @Bean
    public SessionFactory sessionFactory() {
        // with domain entity base package(s)
        return new SessionFactory("de.xxx.demo.neo4j.model");
    }

    @Bean
    public Neo4jTransactionManager transactionManager() {
        return new Neo4jTransactionManager(sessionFactory());
    }

    @Bean
    public Session session() {
        return transactionManager().getSessionFactory().openSession();
    }
}
```


Poor to see, that most of the Neo4J Spring examples in the internet are useless........

**Comment by frant-hartm** [comment]
Hi,

this is an example for Spring Boot's `spring-boot-starter-data-neo4j` - it doesn't need any explicit configuration and should work fine (tests through maven or IDE, running app connecting to local neo4j instance)

Did you make any changes to what is currently in master?

Could you provide your output for `mvn test`?

**Comment by MartinX3** [comment]
Thank you or your fast response. :)

- Okay, I did a fresh git clone https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4.git
- Opened the project with IntelliJ Ultimate 2017.2 (Ubuntu x64)
 - Error with "bean not found" is still happening
- Run mvn test
 - Test runs fine, All 3 passed.

But why IntelliJ is tellling my, that it couldn't autowire "Sessions" because it couldn't find its bean? :(
I want to get away from this weird error. :(

Spring Boot 1.5.6 with Java 8.

**Comment by frant-hartm** [comment]
I see what you mean and can confirm it happens for me as well.

I am not sure if this is SDN's issue (the way we define the thread bound Session bean) or Intellij's issue.

**Comment by MartinX3** [comment]
Yeah, it confuses me and I am a kind of person, which want to resolve every kind of error :)

I get a little bit crazy if i see a red underlined error. :)

**Comment by michael-simons** [comment]
Actually, that still happens with a lot of auto configuration IntelliJ doesn't seem to know of. Closing this nevertheless.
