### ISSUE TITLE
Update to SDN 5 ?

### ISSUE THREAD

**Issue by jexp** [neo4j-examples/movies-java-spring-data-neo4j#19]
After the SF 5.0 SDN5.0 SD2.0 release in Oct 2017, should we update this project too?

**Comment by frant-hartm** [comment]
See the new examples branch, it is on spring 5 and spring boot 2 already (RC or BUILD-SNAPSHOT).

https://github.com/neo4j-examples/movies-java-spring-data-neo4j/tree/new-examples/java-spring-boot-spring-data-neo4j
