### ISSUE TITLE
how to realize and call the function named by findByTitle in MovieRepository 

### ISSUE THREAD

**Issue by songquant** [neo4j-examples/movies-java-spring-data-neo4j#23]
hi ,
I try this project ,feel very interesting. but I encounter a problem：how to realize and call the function named by findByTitle in MovieRepository ， when I call this function ,it is always return NULL, I guest this function need some setup or realise, how to resolve it? please help me ,thank you!

**Comment by jexp** [comment]
You don't have to realize it, it's automatically generated to run a query of finding movies by title.

Just call it. Have a look at the [spring-data-neo4j docs](https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/) for more detail.

**Comment by jexp** [comment]
Oh and of course you need the dataset first in your graph database.
