### ISSUE TITLE
Populate neo4j set value.

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [neo4j-examples/movies-java-spring-data-neo4j#29]
How do I enter data into neo4j? where is the script with the JSON?

CREATE (n:Movie { id: '1', title: 'Assim Falou Zaratustra', released: '2015', tagline: 'Aventura', roles: 'Junior'})

#org.springframework.data.rest.level=DEBUG
#debug: true
#spring.data.neo4j.uri=bolt://localhost
spring.data.neo4j.uri=bolt://54.209.117.178:32888
spring.data.neo4j.username=neo4j
spring.data.neo4j.password=drawers-laws-strains

**Comment by michael-simons** [comment]
You would to this on your Neo4j console or in the Neo4j cypher shell. 

There is no JSON file with data in this project, it uses a prepopulated graph as described here: 
https://github.com/neo4j-examples/movies-java-spring-data-neo4j#quickstart

Hope that helps.
