### ISSUE TITLE
why so many (type = "ACTED_IN") in code ?

### ISSUE THREAD

**Issue by JohnForYang** [neo4j-examples/movies-java-spring-data-neo4j#36]
Since I have defined a Role entity @RelationshipEntity(type = "ACTED_IN")，then I know the field 	#@StartNode private Person person# and #@EndNode private Movie movie# are the two nodes with relationship "ACTED_IN" and also the direction. 
So why there are duplicate type = "ACTED_IN" in Movie entity and Person entity ?

**Comment by michael-simons** [comment]
It's a restriction of Neo4j-OGM (The underlying mapper) at the moment. Sorry.
