### ISSUE TITLE
what  is the 4th sentence really means in ReadMe Quickstart？

### ISSUE THREAD

**Issue by fdrama** [neo4j-examples/movies-java-spring-data-neo4j#40]
> _Run :play movies command, and click and run the Cypher statement to insert the dataset_

what's is this meaning ? i didn't found the play movies, how could i do this step and insert data to the neo4j ,by the way ,i can visit the 7474 and 8080 page

**Comment by michael-simons** [comment]
Please open a browser to http://localhost:7474 and enter `:play movies` into the prompt in the browser. A card will slide down, that looks like this:

<img width="1748" alt="step1" src="https://user-images.githubusercontent.com/526383/59997793-2eeeb980-965e-11e9-93e1-6ac1b8a426a5.png">

Hit the arrow to the right

The card will slide and it will present you the example code:

<img width="1748" alt="step2" src="https://user-images.githubusercontent.com/526383/59997903-5b0a3a80-965e-11e9-993f-cd6062d40b48.png">

Hit the small play button, it will enter the Cypher statement for you into the shell and you can run it.

This is the example data set.
