### ISSUE TITLE
Link on Neo4j Developer Site dead

### ISSUE THREAD

**Issue by chriskamphuis** [neo4j-examples/movies-java-spring-data-neo4j#41]
Link on [Neo4j Developer Site](https://neo4j.com/developer/example-project/) is dead:

https://dl.dropboxusercontent.com/u/14493611/movies_setup.csv

This appears in the code examples.

**Comment by JMHReif** [comment]
Thanks for bringing this to our attention. The link has now been fixed. Please let me know if you have any other issues!
