### ISSUE TITLE
sessionFactory issue

### ISSUE THREAD

**Issue by wurangbo** [neo4j-examples/movies-java-spring-data-neo4j#45]
when i integrate neo4j into my springboot project, I got exception as bellow,
Factory method 'sessionFactory' threw exception; nested exception is java.lang.NullPointerException.

how to fix it.

**Comment by michael-simons** [comment]
This is an example project. If the error still persists, please raise it with Spring Data on https://jira.spring.io/secure/Dashboard.jspa or on our OGM project https://github.com/neo4j/neo4j-ogm/issues. One place is enough, we figure out the rest.
