### ISSUE TITLE
Dependency not found in Maven repo

### ISSUE THREAD

**Issue by prakharkohq** [neo4j-examples/movies-java-spring-data-neo4j#47]
```
	<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-neo4j</artifactId>
			<version>6.0.0-SNAPSHOT</version>
		</dependency>
```

This dependency is not present in maven repo. My build is failing due to this

so i modified this dependency to most recent version still error remains same.

	```
                <dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-neo4j</artifactId>
			<version>5.3.4.RELEASE</version>
		</dependency>
```

My question would be are you able to build the master

**Comment by michael-simons** [comment]
We will update this to 6.0 RC2 next week. You can use the older example in that branch https://github.com/neo4j-examples/movies-java-spring-data-neo4j/tree/sdn5+ogm 

I’ll ping you here.

**Comment by michael-simons** [comment]
Hi @prakharkohq I have added VMWares snapshot repositories. Thanks for your interest in this example! Much appreciated.

**Comment by michael-simons** [comment]
Actually, I'm super happy that you raised the issue. Added a GitHub action so that this doesn't happen again.
