### ISSUE TITLE
Application couldn't be started ?

### ISSUE THREAD

**Issue by dulitharuvin** [neo4j-examples/movies-java-spring-data-neo4j#5]
Error: Could not find or load main class movies.spring.data.neo4j.SampleMovieApplication

the above message is the console message give when i try to run this example project as a Spring Boot Application, my Neo4j version is 2.3.1 and spring version is 4.1

**Comment by nithyanv** [comment]
I am facing same issue with neo4j 3.0.1 version and java version 1.7. Change the java version in pom.xml.
<java.version>1.7</java.version>

Any advice please

**Comment by nithyanv** [comment]
It would seem that executable jar does not contained the class files of the application. Example SampleMovieApplication.class cannot be found inside the executable jar. 

Let me know if you have found a solution to this.

**Comment by marcolettieri** [comment]
Have you solved?

**Comment by mangrish** [comment]
I'm not sure this is a current issue anymore. Can you please try master again and see if it's still not starting? If it's not please reopen.
