### ISSUE TITLE
how could I create dynamic relationship by using sdn6

### ISSUE THREAD

**Issue by Level1Accelerator** [neo4j-examples/movies-java-spring-data-neo4j#58]
use jdk1.8

**Comment by meistermeier** [comment]
In the documentation is a paragraph in this section about using dynamic relationships: https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#mapping.annotations.relationship

You could either use `Enum` or `String` as key types and provide scalar type or collection of the related node type as values.
```
private Map<String, Person> dynamicRelatedPerson;
private Map<MyEnum, Person> dynamicRelatedPerson;
private Map<String, List<Person>> dynamicRelatedPersons;
private Map<MyEnum, List<Person>> dynamicRelatedPersons;
```
All of those above will work.

**Comment by fbiville** [comment]
@Level1Accelerator feel free to reopen this if you still need help
