### ISSUE TITLE
when i use spring-data-neo4j 4.1.5, I can't find http://www.springframework.org/schema/data/neo4j/spring-neo4j.xsd

### ISSUE THREAD

**Issue by pandalin** [neo4j-examples/movies-java-spring-data-neo4j#8]
when i use spring-data-neo4j 4.1.5, 
I can't find http://www.springframework.org/schema/data/neo4j/spring-neo4j.xsd
in my spring-neo4j.xml

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns:neo4j="http://www.springframework.org/schema/data/neo4j"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
        **http://www.springframework.org/schema/data/neo4j** **http://www.springframework.org/schema/data/neo4j/spring-neo4j.xsd**">

**Comment by mangrish** [comment]
Not sure if this is related to this project or https://github.com/spring-projects/spring-data-neo4j. If you still have issues please raise an issue there.
