### ISSUE TITLE
How to save the relationship separately

### ISSUE THREAD

**Issue by wurangbo** [neo4j-examples/movies-java-spring-data-neo4j#95]
Using SDN4， I can save nodes(using NodeEntity) and relationships( using RelationshipEntity) separately.
When I upgraded to SDN6， I can only save nodes(using Node), How can Ioperate the relationship separately？

**Comment by meistermeier** [comment]
Closed because unrelated to the project itself and also asked and answered at https://community.neo4j.com/t/how-to-operate-the-relationship-alone/41614
